export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_MORE_PROJECTS = 'FETCH_MORE_PROJECTS';
export const MORE_PROJECTS = 'MORE_PROJECTS';